### PR TITLE
fix cast_type nil::NilClass when calling write_attribute with a symbol

### LINKED ISSUE #26: write_attribute with symbol attr_name causes: undefined method `cast_type' for nil:NilClass
I stumbled into this when using this with the amoeba gem.

```
activerecord-typedstore (0.5.0) lib/active_record/typed_store/extension.rb:132:in `coder_for'
activerecord-typedstore (0.5.0) lib/active_record/typed_store/extension.rb:142:in `write_attribute'
activerecord (4.2.0) lib/active_record/attribute_methods.rb:373:in `[]='
```
```
def coder_for(attr_name)
    column = self.class.columns_hash[attr_name]
    return unless column.cast_type.is_a?(::ActiveRecord::Type::Serialized)
    column.cast_type.coder
end
```

It seems it calls write_attribute() where "attr_name" is a symbol rather than a string.

Digging into active record it calls to_s on attr_name here: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/attribute_methods/write.rb#L59

Changing:

```
column = self.class.columns_hash[attr_name]
```

to

```
column = self.class.columns_hash[attr_name.to_s]
```

Should resolve the issue.

### PR DESCRIPTION
**Pull request by dannytip**
Fixes #26

### CODE REVIEW

**Comment by byroot** [comment]
Did you tried to write a regression test?

Otherwise LGTM.

**Comment by dannytip** [comment]
Having issues running the test suite currently but i'm working on it.

**Comment by dannytip** [comment]
Test added apologies if they are in the wrong place but the tests fail before my fix and pass after..

**Comment by byroot** [comment]
No that fine. I'll change the wording a bit and ship a new version in a couple minutes. Thanks a lot!

**Comment by byroot** [comment]
A `0.5.1` have been released. Thanks again for your contribution.

**Comment by dannytip** [comment]
No problem at all.  Thanks for releasing the fix so fast.

**Pull request merged**
