### PR TITLE
[WIP] A new version that target Rails 4.2+

### PR DESCRIPTION
**Pull request by yesmeck**
- [x] Remove all compatibility code
- [ ] Use new ActiveRecord API

### CODE REVIEW

**Comment by yesmeck** [comment]
Hi @byroot , I create this WIP PR early so that you can review my code, give me some advice (if you have any time).

**Comment by byroot** [comment]
Sure. Please ping me back when you have a prototype.

**Comment by yesmeck** [comment]
@byroot Do you have any thoughts about the new version that I can add them to the checklist.

**Comment by byroot** [comment]
Not really. But I would recommend to start fresh by totally removing the `extension.rb` file. And of course to take a good look at how `store` is now implemented in Rails.

**Pull request closed without merging**
